# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test, Build & Publish

on:
  push:
    branches: [ "maxime-test-ci-docker" ]

env:
  MAIL_ADDRESS: ${{ secrets.MAIL_ADDRESS }}
  MAIL_TOKEN: ${{ secrets.MAIL_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test
        run: mvn -B test --file pom.xml

      - name: Build
        run: mvn -B package -Dmaven.test.skip --file pom.xml
        
      - name: Clean before publish
        run: mvn clean
      
      - name: Publish
        run: |
          echo -e "${INPUT_KEY}" >__TEMP_INPUT_KEY_FILE 
          chmod 600 __TEMP_INPUT_KEY_FILE 
          scp -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -P "${INPUT_PORT}" $INPUT_OPTIONS -r ${INPUT_SRC} "${INPUT_USER}"@"${INPUT_HOST}":"${INPUT_REMOTE}"
          rm __TEMP_INPUT_KEY_FILE
          
        
